version: '3.8'

networks:
  default:
    external: true
    name: traefik

services:
  monagenceimmo_app:
    container_name: monagenceimmo_app
    build: .
    volumes:
      - ./:/var/www/html
    labels:
      - traefik.enable=true
      - traefik.http.routers.monagenceimmo_app.entrypoints=websecure
      - traefik.http.routers.monagenceimmo_app.rule=Host(`monagenceimmo.${DOMAIN}`)
      - traefik.http.routers.monagenceimmo_app.service=monagenceimmo_app
      - traefik.http.services.monagenceimmo_app.loadbalancer.server.port=80
      - traefik.http.routers.monagenceimmo_app.tls.certresolver=letsencryptresolver

  monagenceimmo_db:
    image: mysql:5.7
    container_name: monagenceimmo_db
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-changeme}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-monagenceimmo}
      MYSQL_USER: ${MYSQL_USER:-monagenceimmo}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-monagenceimmo}
